"""Build ``web/vanilla_graphics.js`` from the shipped romdata dumps.

The custom-window designer needs the stock window graphics for two things:

  1. When the user switches to a window slot they haven't customized yet,
     the editor should show that window's vanilla content as a starting
     point (rather than a blank canvas).
  2. The "Revert to default" button rolls a customized window back to
     vanilla.

Rather than fetch + decode the romdata text files at page load, we
pre-decode them here into a small JS module that ships alongside
borders.js / encoder.js / designer.js.

Output: ``web/vanilla_graphics.js`` -- sets
``window.VANILLA_GRAPHICS = {1: {pixels, palette}, ... 8: {...}}``,
where ``pixels`` is a 1792-byte Uint8Array (32x56, row-major, palette
indices 0..7) and ``palette`` is an array of 8 ``[R, G, B]`` triples
in BGR15 (each 0..31).  Index 0 is transparent (always [0, 0, 0]);
indices 1..7 are the slot colors the configurator already edits.

Run as:
    python scripts/build_vanilla_graphics.py
"""

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from config import window_graphics as wg


def main():
    gfx = wg.parse_hex_dump(
        (REPO_ROOT / "romdata" / "ED0000_MenuWindowGraphics.txt").read_text())
    pal = wg.parse_hex_dump(
        (REPO_ROOT / "romdata" / "ED1C00_MenuWindowPalettes.txt").read_text())
    gfx += [0] * (8 * wg.WINDOW_GRAPHICS_SIZE - len(gfx))
    pal += [0] * (8 * wg.WINDOW_PALETTE_FULL_SIZE - len(pal))

    out_path = REPO_ROOT / "web" / "vanilla_graphics.js"
    with out_path.open('w') as f:
        f.write('// Auto-generated by scripts/build_vanilla_graphics.py -- do not edit.\n')
        f.write('// Stock FF6 window source graphics + palettes, decoded from\n')
        f.write('// romdata/ED0000_*.txt + ED1C00_*.txt.\n//\n')
        f.write('// pixels:  Uint8Array(32 * 56) of palette indices 0..7\n')
        f.write('// palette: 8 entries [R, G, B] (each 0..31; index 0 = transparent)\n\n')
        f.write('window.VANILLA_GRAPHICS = {\n')
        for n in range(1, 9):
            base = (n - 1) * wg.WINDOW_GRAPHICS_SIZE
            pixels = wg.decode_window_sheet(
                gfx[base : base + wg.WINDOW_GRAPHICS_SIZE])
            flat = [px for row in pixels for px in row]
            palette = wg.decode_palette(
                pal[(n - 1) * wg.WINDOW_PALETTE_FULL_SIZE :
                    n * wg.WINDOW_PALETTE_FULL_SIZE])[:8]
            f.write(f'  {n}: {{\n')
            f.write('    pixels: new Uint8Array([\n')
            for r in range(wg.SHEET_HEIGHT):
                row = flat[r * wg.SHEET_WIDTH : (r + 1) * wg.SHEET_WIDTH]
                f.write('      ' + ','.join(str(v) for v in row) + ',\n')
            f.write('    ]),\n')
            f.write('    palette: ' +
                    json.dumps([list(c) for c in palette]) + ',\n')
            f.write('  },\n')
        f.write('};\n')
    print(f"wrote {out_path}")


if __name__ == '__main__':
    main()
