"""Build the hand-curated border presets for the web designer.

The custom-window designer asks the user to upload a 32x32 texture plus
pick a "border" -- a 32x24 strip of frame pieces (corner / edge / gauge
marker) that goes underneath the texture in the final 32x56 source sheet.

This script generates that border preset set.  For each chosen vanilla
window, we take the bottom 4x3 tile region of its source sheet and
reindex each pixel to its luminosity rank within that window's source
palette:

  - vanilla index 0           -> output index 0  (transparent)
  - lightest vanilla color    -> output index 1
  - 2nd lightest              -> output index 2
  ...
  - darkest vanilla color     -> output index 7

That lets the border carry the full anti-aliasing / shading nuance of
the original (bolt highlights, panel transitions, gauge shading) instead
of a two-color caricature.  The texture quantizer in the designer also
sorts its 7 user-chosen colors light->dark into slots 1..7, so the
border's per-pixel rank automatically maps onto the matching slot of
whatever palette the user's texture produced.

Output: ``web/borders.js`` -- a non-module script that sets
``window.BORDER_PRESETS`` (matches the rest of ``web/main.js``).

Run as:
    python scripts/build_borders.py
"""

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from config import window_graphics as wg


PRESET_SOURCES = [
    # key,        vanilla window, displayed name
    ('rounded',   1, 'Rounded (W1)'),
    ('bolted',    2, 'Bolted (W2)'),
    ('wood',      4, 'Wood (W4)'),
    ('parchment', 5, 'Parchment (W5)'),
    ('stone',     6, 'Stone (W6)'),
    ('ornate',    8, 'Ornate (W8)'),
]


def luminosity(rgb):
    r, g, b = rgb
    return 0.299 * r + 0.587 * g + 0.114 * b


def _load_romdata():
    gfx = wg.parse_hex_dump(
        (REPO_ROOT / "romdata" / "ED0000_MenuWindowGraphics.txt").read_text())
    pal = wg.parse_hex_dump(
        (REPO_ROOT / "romdata" / "ED1C00_MenuWindowPalettes.txt").read_text())
    gfx += [0] * (8 * wg.WINDOW_GRAPHICS_SIZE - len(gfx))
    pal += [0] * (8 * wg.WINDOW_PALETTE_FULL_SIZE - len(pal))
    return gfx, pal


def extract_border(n, gfx_all, pal_all):
    """Return the bottom 24 rows of window n's sheet, reindexed by luminosity rank."""
    base = (n - 1) * wg.WINDOW_GRAPHICS_SIZE
    pixels = wg.decode_window_sheet(gfx_all[base : base + wg.WINDOW_GRAPHICS_SIZE])
    pal = wg.decode_palette(
        pal_all[(n - 1) * wg.WINDOW_PALETTE_FULL_SIZE :
                n * wg.WINDOW_PALETTE_FULL_SIZE])

    # Bottom 24 rows of the 56-row sheet -- everything past row 32.
    bottom = [row[:] for row in pixels[32:]]

    # Vanilla indices 1..7 sorted by luminosity (lightest first); the
    # position in this list + 1 becomes the output index (so lightest -> 1,
    # darkest -> 7).
    rank = {
        idx: pos + 1
        for pos, idx in enumerate(
            sorted(range(1, 8), key=lambda i: -luminosity(pal[i])))
    }

    out = []
    used = set()
    for row in bottom:
        out_row = []
        for px in row:
            v = 0 if px == 0 else rank[px]
            out_row.append(v)
            used.add(v)
        out.append(out_row)
    return out, used


def main():
    gfx_all, pal_all = _load_romdata()
    presets = {}
    for key, n, label in PRESET_SOURCES:
        grid, used = extract_border(n, gfx_all, pal_all)
        presets[key] = {'name': label, 'pixels': grid}
        print(f"  {key:8s} -> {label}  uses indices {sorted(used)}")

    presets['plain'] = {
        'name': 'Plain (no border)',
        'pixels': [[0] * 32 for _ in range(24)],
    }

    out_path = REPO_ROOT / "web" / "borders.js"
    order = ['plain'] + [key for key, _, _ in PRESET_SOURCES]
    with out_path.open('w') as f:
        f.write('// Auto-generated by scripts/build_borders.py -- do not edit.\n')
        f.write('// 32x24 border presets, reindexed by luminosity rank:\n')
        f.write('//   0 = transparent, 1 = lightest, 7 = darkest.\n')
        f.write('// Each "pixels" field is a Uint8Array of 768 entries, row-major.\n\n')
        f.write('window.BORDER_PRESETS = {\n')
        for key in order:
            flat = [px for row in presets[key]['pixels'] for px in row]
            f.write(f'  {key}: {{\n')
            f.write(f'    name: {json.dumps(presets[key]["name"])},\n')
            f.write('    pixels: new Uint8Array([\n')
            for r in range(24):
                row = flat[r * 32 : (r + 1) * 32]
                f.write('      ' + ','.join(str(v) for v in row) + ',\n')
            f.write('    ]),\n')
            f.write('  },\n')
        f.write('};\n')
        f.write('window.BORDER_PRESETS_ORDER = ' + json.dumps(order) + ';\n')
    print(f"wrote {out_path}")


if __name__ == '__main__':
    main()
