"""Door-rando atlas: static description of the vanilla world.

The atlas is immutable and ROM-free. It has two layers:

- compiled.py  - GENERATED by tools/compile_atlas.py from the ROM data
  dumps: one record per vanilla exit (kind/map/position/destination) and
  the vanilla partner table (coordinate-derived, curation applied).
- curation.py  - hand-maintained semantics that coordinates cannot
  express: partner overrides (each with a reason tag), unused exits, and
  intentionally asymmetric pairings.

tools/compile_atlas.py --check proves compiled+curation agree with the
data/map_exit_extra.exit_data partner column exactly; run it after
editing curation.py, and re-run without --check to regenerate
compiled.py. Exit *descriptions* live in data/map_exit_extra.py (the
description accessors below delegate).
"""

from doors.atlas.compiled import EXIT_RECORDS, PARTNERS, TRAP_RECORDS, EVENT_DOOR_RECORDS
from doors.atlas import curation


def exit_record(exit_id):
    """Record for a vanilla exit id (0-1280), or None."""
    return EXIT_RECORDS.get(exit_id)


def vanilla_partner(exit_id):
    """The exit you return through in the vanilla game (None if unused)."""
    return PARTNERS.get(exit_id)


def exit_map(exit_id):
    """SNES map id an exit sits on."""
    rec = EXIT_RECORDS.get(exit_id)
    return rec['map'] if rec else None


def exit_position(exit_id):
    """(x, y) tile of an exit (first tile of a long exit's span)."""
    rec = EXIT_RECORDS.get(exit_id)
    return (rec['x'], rec['y']) if rec else None


def trap_record(trap_id):
    """Location record for a one-way exit (2000-2999 or '2035a' variants)."""
    return TRAP_RECORDS.get(trap_id)


def event_door_record(door_id):
    """Location record for an event-tile door (1500-1999, +4000 copies)."""
    return EVENT_DOOR_RECORDS.get(door_id)


def room_name(room_id):
    """Atlas name for a room_data id (see doors/atlas/room_names.py)."""
    from doors.atlas.room_names import ROOM_NAMES
    return ROOM_NAMES.get(room_id)


def description(exit_id):
    """Human name of an exit (exit_data description column)."""
    from data.map_exit_extra import exit_data
    entry = exit_data.get(exit_id)
    return entry[1] if entry else None


def exit_description(exit_id):
    """Human name for any door/trap/pit/event-tile id, with a stable
    fallback -- the one naming chain for spoiler logs and debug output."""
    from data.map_exit_extra import exit_data
    from data.event_exit_data import event_exit_info
    if exit_id in exit_data:
        return exit_data[exit_id][1]
    if exit_id in event_exit_info:
        return event_exit_info[exit_id][4]
    return f"Door {exit_id}"
