"""Door-rando atlas: static description of the vanilla world (rewrite Stage A).

The atlas is immutable and ROM-free. It has two layers:

- compiled.py  - GENERATED by tools/compile_atlas.py from the ROM data
  dumps: one record per vanilla exit (kind/map/position/destination) and
  the vanilla partner table (coordinate-derived, curation applied).
- curation.py  - hand-maintained semantics that coordinates cannot
  express: partner overrides (each with a reason tag), unused exits, and
  intentionally asymmetric pairings.

tools/compile_atlas.py --check proves compiled+curation reproduce the
legacy data/map_exit_extra.exit_data partner column exactly; run it after
editing curation.py, and re-run without --check to regenerate compiled.py.

During the staged rewrite the legacy tables remain the live data source;
this package is the parallel, machine-checked source that later stages
build on. Exit *descriptions* still live in data/map_exit_extra.py (the
description accessor below delegates) until the dependency direction
flips in Stage B.
"""

from doors.atlas.compiled import EXIT_RECORDS, PARTNERS
from doors.atlas import curation


def exit_record(exit_id):
    """Record for a vanilla exit id (0-1280), or None."""
    return EXIT_RECORDS.get(exit_id)


def vanilla_partner(exit_id):
    """The exit you return through in the vanilla game (None if unused)."""
    return PARTNERS.get(exit_id)


def exit_map(exit_id):
    """SNES map id an exit sits on."""
    rec = EXIT_RECORDS.get(exit_id)
    return rec['map'] if rec else None


def exit_position(exit_id):
    """(x, y) tile of an exit (first tile of a long exit's span)."""
    rec = EXIT_RECORDS.get(exit_id)
    return (rec['x'], rec['y']) if rec else None


def description(exit_id):
    """Human name of an exit. Delegates to the legacy table for now."""
    from data.map_exit_extra import exit_data
    entry = exit_data.get(exit_id)
    return entry[1] if entry else None
